version: "3.7"
services:
  db:
    image: postgres:15
    container_name: chessonlinedb
    env_file:
      - non_dev.env
    ports:
      - "5432:5432"

  chessOnline:
    build:
      context: .
    container_name: chess_online_app
    env_file:
      - non_dev.env
    depends_on:
      - db
#    command: ["/chessOnline/docker/app.sh"]
    ports:
      - "8080:8080"



